on: push
jobs:
  cocos-action:
    runs-on: windows-latest
    steps:
      - name: execute build
        run: |
         D:\a\GitHubFlow\GitHubFlow\.github\cocos\CocosCreator.exe --path C:\GitHubWorkFlow --build "platform=android;debug=true;autoCompile=true;startScene=db://assets/Scene/helloworld.fire;template=default;appABIs=['armeabi-v7a']"
